API_KEY = 'hqkkwu5xy7s7k1p9'
ACCESS_TOKEN = 'zgVRq1eD1SqLCBzrM2HDiBOwIIXGRWY9'
LOG_FILE_PATH = '/Users/nagi/Projects/Trading/LiveCode/UniAutoTraderZerodha/app.log'
INSTRUMENT_TOKEN='15776514,260105,256265'
EXPIRY_WEEK='w3'
SYMBOLS_PATH = '/Users/nagi/Projects/Trading/LiveCode/UniAutoTraderZerodha/today_symbols.json'