LOG_FILE_PATH = '/Users/nagi/Projects/Trading/LiveCode/UniAutoTraderZerodha/app.log'
RMQ_HOST = 'localhost'
EXCHANGE = 'BANKNIFTY'
INSTRUMENT_TOKEN='260105'
EXPIRY = '17-Jan-2024'
LOT_QUANTITY = 990
LEG_QTY=900
CLOSEST_PREMIUM=200
STRATEGY_CODE = 'ST02'
RANGE_START_TIME = '09:36'
RANGE_END_TIME = '09:45'
ENTRY_TIME = '09:36'
EXIT_TIME = '14:56'
STOP_LOSS_PERCENTAGE = '12'
NO_OF_ENTRIES = '1'
SESSION_ORDERS_FILE = "/Users/nagi/Projects/Trading/LiveCode/UniAutoTrader/StrategyTwo-RangeBreakout/session_orders.json"
SYMBOLS_PATH = '/Users/nagi/Projects/Trading/LiveCode/UniAutoTraderZerodha/today_symbols.json'
API_KEY = 'hqkkwu5xy7s7k1p9'
API_SECRET = 'q3ytb4scipcrav36owmqn21ztrfac7ep'
USER_ID = 'PS9881'
PASSWORD = 'Srinath123*'
TOTP_KEY = '2X3UA42KWDBLVMU4J3UZAMYVLE3KS57C'
ACCESS_TOKEN = 'zgVRq1eD1SqLCBzrM2HDiBOwIIXGRWY9'
